---
- name: configure ubuntu
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288
  notify: re-read sysctl config
- name: add ssh key
  shell: "ssh-keygen -q -N '' -f {{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  notify: store public ssh key
- name: configure standard tools
  copy:
    src: configuration/git/.gitconfig
    dest: "{{ lookup('env', 'HOME') }}/"
- name: configure editors
  copy:
    src: configuration/editors/.editorconfig
    dest: "{{ lookup('env', 'HOME') }}/"
- name: generate standard repository folder structure
  file:
    path: "{{ lookup('env', 'HOME') }}/repos/{{ item }}/"
    state: directory
  loop:
    - home
    - work
    - community
    - tryout
- name: add utility scripts
  block:
    - name: ensure utility scripts folder exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.scripts/"
        mode: u+x
        state: directory
    - name: copy utility scripts
      copy:
        src: utility-scripts/github-pull-request.sh
        dest: "{{ lookup('env', 'HOME') }}/.scripts/"
    - name: source utility scripts
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        line: "export PATH=$PATH:{{ lookup('env', 'HOME') }}/.scripts/"
# TODO:
# - docker + compose
# - vpn
# - team viewer
# - flameshot config
# - fix guake
