---
- name: configure ubuntu
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288
  notify: re-read sysctl config
- name: add ssh key
  shell: "ssh-keygen -q -N '' -f {{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  notify: store public ssh key
- name: configure standard tools
  copy:
    src: configuration/git/.gitconfig
    dest: "{{ lookup('env', 'HOME') }}/"
- name: configure editors
  copy:
    src: configuration/editors/.editorconfig
    dest: "{{ lookup('env', 'HOME') }}/"
# TODO:
# - logins
# - docker + compose
# - java tools
# - vpn
# - team viewer
# - flameshot config
# - pull request script
# - intellij installation
# - standard folder structure
# - autokey texts
