---
- name: install node development tools
  block:
    - name: install nvm
      become: false
      block:
        - name: run the nvm installation
          shell: >
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          args:
            creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
