---
- name: install apt tools
  apt:
    name: "{{ item }}"
  loop:
    - default-jdk
    - openjdk-8-jdk
    - maven
- name: install snap tools
  community.general.snap:
    name: "{{ item }}"
    classic: yes
  loop:
    - intellij-idea-community
# TODO:
# - ssh key
# - git config
# - filesystem stuff
# - favoriten, dark mode
# - logins
# - docker + compose
# - java tools
# - vpn
# - team viewer
# - flameshot config
# - pull request script
# - editorconfig
# - intellij installation
# - standard folder structure
# - autokey texts
