---
- name: install command-line productivity tools
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - jq
    - unzip
    - curl
    - vim
    - htop
    - xclip
- name: install standard ui productivity tools
  apt:
    name: "{{ item }}"
  loop:
    - guake
    - autokey-gtk
    - flameshot
    - peek
- name: install ulauncher ui productivity tool
  block:
    - name: add apt repo
      apt_repo:
        repo: ppa:agornostal/ulauncher
        update: yes
    - name: run the ulauncher installation
      apt:
        name: ulauncher
