---
- name: update packages cache
  apt:
    name: wget
    update_cache: yes
- name: install command-line productivity tools
  apt:
    name: "{{ item }}"
  loop:
    - jq
    - unzip
    - curl
    - vim
    - htop
    - xclip
    - python3-pip
- name: install standard ui productivity tools
  apt:
    name: "{{ item }}"
  loop:
    - guake
    - autokey-gtk
    - flameshot
    - peek
- name: install ulauncher ui productivity tool
  block:
    - name: add ulauncher apt repo
      apt_repository:
        repo: ppa:agornostal/ulauncher
        update_cache: yes
    - name: run the ulauncher installation
      apt:
        name: ulauncher
    - name: install packages required for ulauncher extensions
      block:
        - name: install mlocate (for the chrome bookmarks extension)
          apt:
            name: mlocate
        - name: install todoist-python (for the todoist extension)
          pip:
            name: todoist-python
    - name: configure ulauncher
      become: false
      copy:
        src: configuration/ulauncher/{{ item }}.json
        dest: "{{ lookup('env', 'HOME') }}/.config/ulauncher/"
      loop:
        - settings
        - extensions
- name: autostart productivity tools
  become: false
  copy:
    src: autostart/{{ item }}.desktop
    dest: "{{ lookup('env', 'HOME') }}/autostart/"
  loop:
    - autokey
    - guake
    - ulauncher
