---
- name: update packages cache
  apt:
    name: wget
    update_cache: yes
- name: install command-line productivity tools
  apt:
    name: "{{ item }}"
  loop:
    - jq
    - unzip
    - curl
    - vim
    - htop
    - xclip
- name: install standard ui productivity tools
  apt:
    name: "{{ item }}"
  loop:
    - guake
    - autokey-gtk
    - flameshot
    - peek
- name: install ulauncher ui productivity tool
  block:
    - name: add ulauncher apt repo
      apt_repository:
        repo: ppa:agornostal/ulauncher
        update_cache: yes
    - name: run the ulauncher installation
      apt:
        name: ulauncher
- name: autostart productivity tools
  copy:
    src: autostart/{{ item }}.desktop
    dest: "{{ lookup('env', 'HOME') }}/autostart/"
  loop:
    - autokey
    - guake
    - ulauncher
